consul:
  image: autopilotpattern/consul:0.7r0.7
  restart: always
  dns:
    - 127.0.0.1
  labels:
    - triton.cns.services=consul
  ports:
    - "8500:8500"
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui
prometheus:
    image: autopilotpattern/prometheus:1.3.0r1.0
    mem_limit: 128m
    restart: always
    ports:
      - "9090:9090"
    links:
      - consul:consul
    environment:
      - CONSUL=consul
influxdb:
  image: autopilotpattern/influxdb
  ports:
    - "8086:8086"
    - "8083:8083"
  restart: always
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_REPORTING_DISABLED=true
    - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    - INFLUXDB_HTTP_LOG_ENABLED=false
    - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
serializer:
  build: ./serializer
  links:
    - consul:consul
  environment:
    - PORT=10000
    - CONSUL_HOST=consul
    - INFLUXDB_USER=root
    - INFLUXDB_PWD=root
  expose:
    - "10000"
  restart: always
frontend:
  build: ./frontend
  links:
    - consul:consul
  environment:
    - CONSUL_HOST=consul
    - PORT=10001
  ports:
    - 10001:10001
  restart: always
smartthings:
  build: ./smartthings
  expose:
    - "8080"
  environment:
    - PORT=8080
  restart: always
temperature:
  build: ./sensor
  links:
    - consul:consul
    - smartthings:smartthings
  environment:
    - SENSOR_TYPE=temperature
    - PORT=8080
    - SMARTTHINGS_HOST=smartthings
    - SMARTTHINGS_PORT=8080
    - CONSUL_HOST=consul
  restart: always
motion:
  build: ./sensor
  links:
    - consul:consul
    - smartthings:smartthings
  environment:
    - SENSOR_TYPE=motion
    - PORT=8080
    - SMARTTHINGS_HOST=smartthings
    - SMARTTHINGS_PORT=8080
    - CONSUL_HOST=consul
  restart: always
humidity:
  build: ./sensor
  links:
    - consul:consul
    - smartthings:smartthings
  environment:
    - SENSOR_TYPE=humidity
    - PORT=8080
    - SMARTTHINGS_HOST=smartthings
    - SMARTTHINGS_PORT=8080
    - CONSUL_HOST=consul
    - CONSUL=consul
  restart: always
